apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxl-job
    component: xxl-job
  name: xxl-job
  namespace: miyu
spec:
  ports:
    - name: http-49999
      port: 49999
      targetPort: 49999
  selector:
    app: xxl-job
    component: xxl-job
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.229