apiVersion: v1 #版本号
kind: Service #资源类型
metadata: #元数据
  labels: # 标签  kubectl get nodes --show-labels
    app: nacos
    component: nacos
  name: nacos  #资源名称
  namespace: miyu #命名空间
spec: #描述
  ports: #端口信息
    - name: http-8848
      port: 8848 #service端口
      targetPort: 8848 #pod端口
    - name: http-9848
      port: 9848 #service端口
      targetPort: 9848 #pod端\
    - name: http-9849
      port: 9849 #service端口
      targetPort: 9849 #pod端口
  selector: #标签选择器
    app: nacos
    component: nacos
    tier: backend
  type: LoadBalancer #服务类型  ClusterIp/NodePort/LoadBalancer
                      #ClusterIp:仅供内部访问
                      #nodePort：将service通过指定的Node上的端口暴露给外部
                      #LoadBalancer：使用外接的负载均衡器完成到服务的负载分发
                      #可以通过该命令查看地址池 kubectl get IPAddressPool -n metallb-system
  loadBalancerIP: 192.168.2.225 #指定IP