apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-wms
    component: miyu-wms
  name: miyu-wms
  namespace: miyu
spec:
  ports:
    - name: http-40000
      port: 40000
      targetPort: 40000
  selector:
    app: miyu-wms
    component: miyu-wms
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227