apiVersion: v1
kind: Service
metadata:
  labels:
    app: yudao-gateway
    component: yudao-gateway
  name: yudao-gateway
  namespace: miyu
spec:
  ports:
    - name: http-48080
      port: 48080
      targetPort: 48080
  selector:
    app: yudao-gateway
    component: yudao-gateway
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.226