apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-mcs
    component: miyu-mcs
  name: miyu-mcs
  namespace: miyu
spec:
  ports:
    - name: http-48090
      port: 48090
      targetPort: 48090
  selector:
    app: miyu-mcs
    component: miyu-mcs
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227