apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-pms
    component: miyu-pms
  name: miyu-pms
  namespace: miyu
spec:
  ports:
    - name: http-48100
      port: 48100
      targetPort: 48100
  selector:
    app: miyu-pms
    component: miyu-pms
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227