apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-qms
    component: miyu-qms
  name: miyu-qms
  namespace: miyu
spec:
  ports:
    - name: http-40091
      port: 40091
      targetPort: 40091
  selector:
    app: miyu-qms
    component: miyu-qms
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227