spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        ## system-server 服务
        - id: system-admin-api # 路由的编号
          uri: grayLb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/system/**
          filters:
              - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: system-app-api # 路由的编号
          uri: grayLb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/system/**
          filters:
              - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
        ## infra-server 服务
        - id: infra-admin-api # 路由的编号
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/infra/**
          filters:
              - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-app-api # 路由的编号
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/infra/**
          filters:
              - RewritePath=/app-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-spring-boot-admin # 路由的编号（Spring Boot Admin）
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin/**
        - id: infra-websocket # 路由的编号（WebSocket）
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/infra/ws/**
        ## member-server 服务
        - id: member-admin-api # 路由的编号
          uri: grayLb://member-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/member/**
          filters:
            - RewritePath=/admin-api/member/v3/api-docs, /v3/api-docs
        - id: member-app-api # 路由的编号
          uri: grayLb://member-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/member/**
          filters:
            - RewritePath=/app-api/member/v3/api-docs, /v3/api-docs
        ## bpm-server 服务
        - id: bpm-admin-api # 路由的编号
          uri: grayLb://bpm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/bpm/**
          filters:
              - RewritePath=/admin-api/bpm/v3/api-docs, /v3/api-docs
        ## report-server 服务
        - id: report-admin-api # 路由的编号
          uri: grayLb://report-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/report/**
          filters:
            - RewritePath=/admin-api/report/v3/api-docs, /v3/api-docs
        - id: report-jimu # 路由的编号（积木报表）
          uri: grayLb://report-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/jmreport/**
        ## pay-server 服务
        - id: pay-admin-api # 路由的编号
          uri: grayLb://pay-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/pay/**
          filters:
            - RewritePath=/admin-api/pay/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: pay-app-api # 路由的编号
          uri: grayLb://pay-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/pay/**
          filters:
            - RewritePath=/app-api/pay/v3/api-docs, /v3/api-docs
        ## mp-server 服务
        - id: mp-admin-api # 路由的编号
          uri: grayLb://mp-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/mp/**
          filters:
            - RewritePath=/admin-api/mp/v3/api-docs, /v3/api-docs
        ## product-server 服务
        - id: product-admin-api # 路由的编号
          uri: grayLb://product-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/product/**
          filters:
            - RewritePath=/admin-api/product/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: product-app-api # 路由的编号
          uri: grayLb://product-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/product/**
          filters:
            - RewritePath=/app-api/product/v3/api-docs, /v3/api-docs
        ## promotion-server 服务
        - id: promotion-admin-api # 路由的编号
          uri: grayLb://promotion-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/promotion/**
          filters:
            - RewritePath=/admin-api/promotion/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: promotion-app-api # 路由的编号
          uri: grayLb://promotion-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/promotion/**
          filters:
            - RewritePath=/app-api/promotion/v3/api-docs, /v3/api-docs
        ## trade-server 服务
        - id: trade-admin-api # 路由的编号
          uri: grayLb://trade-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/trade/**
          filters:
            - RewritePath=/admin-api/trade/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: trade-app-api # 路由的编号
          uri: grayLb://trade-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/trade/**
          filters:
            - RewritePath=/app-api/trade/v3/api-docs, /v3/api-docs
        ## statistics-server 服务
        - id: statistics-admin-api # 路由的编号
          uri: grayLb://statistics-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/statistics/**
          filters:
            - RewritePath=/admin-api/statistics/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## erp-server 服务
        - id: erp-admin-api # 路由的编号
          uri: grayLb://erp-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/erp/**
          filters:
            - RewritePath=/admin-api/erp/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## crm-server 服务
        - id: crm-admin-api # 路由的编号
          uri: grayLb://crm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/crm/**
          filters:
            - RewritePath=/admin-api/crm/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## miyu-wms 服务
        - id: wms-admin-api # 路由的编号
          uri: grayLb://wms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/wms/**
          filters:
            - RewritePath=/admin-api/wms/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: wms-app-api # 路由的编号
          uri: grayLb://wms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/wms/**
          filters:
            - RewritePath=/app-api/wms/v3/api-docs, /v3/api-docs
        - id: wms-rpc-api # 路由的编号
          uri: grayLb://wms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/rpc-api/wms/**
          filters:
            - RewritePath=/rpc-api/wms/v3/api-docs, /v3/api-docs
        ## miyu-pdm 服务
        - id: pdm-admin-api # 路由的编号
          uri: grayLb://pdm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/pdm/**
          filters:
            - RewritePath=/admin-api/erp/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## mcs-server 服务
        - id: mcs-admin-api # 路由的编号
          uri: grayLb://mcs-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/mcs/**
          filters:
            - RewritePath=/admin-api/mcs/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: dms-admin-api # 路由的编号
          uri: grayLb://mcs-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/dms/**
          filters:
            - RewritePath=/admin-api/dms/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## miyu-qms 服务
        - id: qms-admin-api # 路由的编号
          uri: grayLb://qms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/qms/**
          filters:
            - RewritePath=/admin-api/qms/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: qms-app-api # 路由的编号
          uri: grayLb://qms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/qms/**
          filters:
            - RewritePath=/app-api/qms/v3/api-docs, /v3/api-docs
        ## miyu-dc 服务
        - id: dc-admin-api # 路由的编号
          uri: grayLb://dc-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/dc/**
          filters:
            - RewritePath=/admin-api/dc/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: dc-app-api # 路由的编号
          uri: grayLb://dc-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/dc/**
          filters:
            - RewritePath=/app-api/dc/v3/api-docs, /v3/api-docs
        ## miyu-dm 服务
        - id: dm-admin-api # 路由的编号
          uri: grayLb://dm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/dm/**
          filters:
            - RewritePath=/admin-api/dm/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: dm-app-api # 路由的编号
          uri: grayLb://dm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/dm/**
          filters:
            - RewritePath=/app-api/dm/v3/api-docs, /v3/api-docs
        ## miyu-ppm 服务
        - id: ppm-admin-api # 路由的编号
          uri: grayLb://ppm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/ppm/**
          filters:
            - RewritePath=/admin-api/ppm/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: ppm-app-api # 路由的编号
          uri: grayLb://dm-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/ppm/**
          filters:
            - RewritePath=/app-api/ppm/v3/api-docs, /v3/api-docs

        ## miyu-pms 服务
        - id: pms-admin-api # 路由的编号
          uri: grayLb://pms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/pms/**
          filters:
            - RewritePath=/admin-api/pms/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: pms-app-api # 路由的编号
          uri: grayLb://pms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/pms/**
          filters:
            - RewritePath=/app-api/pms/v3/api-docs, /v3/api-docs
        ## macs 门禁服务
        - id: macs-cloud # 路由的编号
          uri: grayLb://macs-cloud
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/macs/**
          filters:
            - RewritePath=/admin-api/macs/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## miyu-mcc 服务
        - id: mcc-admin-api # 路由的编号
          uri: grayLb://mcc-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/mcc/**
          filters:
            - RewritePath=/admin-api/mcc/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: mcc-app-api # 路由的编号
          uri: grayLb://mcc-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/mcc/**
          filters:
            - RewritePath=/app-api/mcc/v3/api-docs, /v3/api-docs
        ## miyu-es 服务
        - id: es-admin-api # 路由的编号
          uri: grayLb://es-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/es/**
          filters:
            - RewritePath=/admin-api/es/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: es-app-api # 路由的编号
          uri: grayLb://es-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/es/**
          filters:
            - RewritePath=/app-api/es/v3/api-docs, /v3/api-docs
        ## miyu-eg 服务
        - id: eg-admin-api # 路由的编号
          uri: grayLb://eg-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/eg/**
          filters:
            - RewritePath=/admin-api/eg/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v2/api-docs
        - id: eg-app-api # 路由的编号
          uri: grayLb://eg-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/eg/**
          filters:
            - RewritePath=/app-api/eg/v3/api-docs, /v3/api-docs
        ## knifetool-server 服务
        - id: knifetool-admin-api # 路由的编号
          uri: grayLb://knifetool-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/knifetool/**
          filters:
            - RewritePath=/admin-api/knifetool/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: tms-admin-api # 路由的编号
          uri: grayLb://tms-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/tms/**
          filters:
            - RewritePath=/admin-api/tms/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: infra-server
        service-name: infra-server
        url: /admin-api/infra/v3/api-docs
      - name: member-server
        service-name: member-server
        url: /admin-api/member/v3/api-docs
      - name: bpm-server
        service-name: bpm-server
        url: /admin-api/bpm/v3/api-docs
      - name: pay-server
        service-name: pay-server
        url: /admin-api/pay/v3/api-docs
      - name: mp-server
        service-name: mp-server
        url: /admin-api/mp/v3/api-docs
      - name: product-server
        service-name: product-server
        url: /admin-api/product/v3/api-docs
      - name: promotion-server
        service-name: promotion-server
        url: /admin-api/promotion/v3/api-docs
      - name: trade-server
        service-name: trade-server
        url: /admin-api/trade/v3/api-docs
      - name: statistics-server
        service-name: statistics-server
        url: /admin-api/statistics/v3/api-docs
      - name: erp-server
        service-name: erp-server
        url: /admin-api/erp/v3/api-docs
      - name: crm-server
        service-name: crm-server
        url: /admin-api/crm/v3/api-docs
      - name: wms-server
        service-name: wms-server
        url: /admin-api/wms/v3/api-docs
      - name: pdm-server
        service-name: pdm-server
        url: /admin-api/pdm/v3/api-docs
      - name: mcs-server
        service-name: mcs-server
        url: /admin-api/mcs/v3/api-docs
      - name: dms-server
        service-name: mcs-server
        url: /admin-api/dms/v3/api-docs
      - name: ppm-server
        service-name: ppm-server
        url: /admin-api/ppm/v3/api-docs
      - name: qms-server
        service-name: qms-server
        url: /admin-api/qms/v3/api-docs
      - name: dm-server
        service-name: dm-server
        url: /admin-api/dm/v3/api-docs
      - name: pms-server
        service-name: pms-server
        url: /admin-api/pms/v3/api-docs
      - name: dc-server
        service-name: dc-server
        url: /admin-api/dc/v3/api-docs
      - name: macs-cloud
        service-name: macs-cloud
        url: /admin-api/macs/v3/api-docs
      - name: mcc-server
        service-name: mcc-server
        url: /admin-api/mcc/v3/api-docs
      - name: es-server
        service-name: es-server
        url: /admin-api/es/v3/api-docs
      - name: eg-server
        service-name: eg-server
        url: /admin-api/eg/v3/api-docs
      - name: knifetool-server
        service-name: knifetool-server
        url: /admin-api/knifetool/v3/api-docs
      - name: tms-server
        service-name: tms-server
        url: /admin-api/tms/v3/api-docs
--- #################### 芋道相关配置 ####################

yudao:
  info:
    version: 1.0.0
