apiVersion: v1
kind: Service
metadata:
  labels:
    app: yudao-module-system
    component: yudao-module-system
  name: yudao-module-system
  namespace: miyu
spec:
  ports:
    - name: http-48081
      port: 48081
      targetPort: 48081
  selector:
    app: yudao-module-system
    component: yudao-module-system
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227