apiVersion: v1
kind: Service
metadata:
  labels:
    app: yudao-module-bpm
    component: yudao-module-bpm
  name: yudao-module-bpm
  namespace: miyu
spec:
  ports:
    - name: http-48083
      port: 48083
      targetPort: 48083
  selector:
    app: yudao-module-bpm
    component: yudao-module-bpm
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227