apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-ppm
    component: miyu-ppm
  name: miyu-ppm
  namespace: miyu
spec:
  ports:
    - name: http-40001
      port: 40001
      targetPort: 40001
  selector:
    app: miyu-ppm
    component: miyu-ppm
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227