apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-cloud-macs
    component: miyu-cloud-macs
  name: miyu-cloud-macs
  namespace: miyu
spec:
  ports:
    - name: http-7011
      port: 7011
      targetPort: 7011
  selector:
    app: miyu-cloud-macs
    component: miyu-cloud-macs
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227