apiVersion: v1
kind: Service
metadata:
  labels:
    app: miyu-pdm
    component: miyu-pdm
  name: miyu-pdm
  namespace: miyu
spec:
  ports:
    - name: http-50000
      port: 50000
      targetPort: 50000
  selector:
    app: miyu-pdm
    component: miyu-pdm
    tier: backend
  type: LoadBalancer
  loadBalancerIP: 192.168.2.227